In [1]:
pip install us

Requirement already satisfied: us in /Users/aditya/anaconda3/lib/python3.11/site-packages (3.1.1)
Requirement already satisfied: jellyfish==0.11.2 in /Users/aditya/anaconda3/lib/python3.11/site-packages (from us) (0.11.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import us
import pandas as pd
import numpy as np
import requests
import json

In [3]:
states = us.states.STATES
state_abbr = []
fips = []

for state in states:
    state_abbr.append(state.abbr)
    fips.append(state.fips)

state_abbr = [name.lower() for name in state_abbr]

states.append("District of Columbia")
state_abbr.append("dc")
fips.append("11")

covid_deaths_2020_df = pd.DataFrame({'State': states, 'State Abbreviation':state_abbr, 'FIPS':fips})
covid_deaths_2020_df ["Total Population 2021"] = ""
covid_deaths_2020_df ["Total Cases 2020"] = ""
covid_deaths_2020_df ["Total Hospitalized 2020"] = ""
covid_deaths_2020_df ["Total Deaths 2020"] = ""

covid_deaths_2020_df

,State,State Abbreviation,FIPS,Total Population 2021,Total Cases 2020,Total Hospitalized 2020,Total Deaths 2020
0,Alabama,al,01,,,,
1,Alaska,ak,02,,,,
2,Arizona,az,04,,,,
3,Arkansas,ar,05,,,,
4,California,ca,06,,,,
5,Colorado,co,08,,,,
6,Connecticut,ct,09,,,,
7,Delaware,de,10,,,,
8,Florida,fl,12,,,,
9,Georgia,ga,13,,,,
10,Hawaii,hi,15,,,,
11,Idaho,id,16,,,,
12,Illinois,il,17,,,,
13,Indiana,in,18,,,,
14,Iowa,ia,19,,,,
15,Kansas,ks,20,,,,
16,Kentucky,ky,21,,,,
17,Louisiana,la,22,,,,
18,Maine,me,23,,,,
19,Maryland,md,24,,,,
20,Massachusetts,ma,25,,,,
21,Michigan,mi,26,,,,
22,Minnesota,mn,27,,,,
23,Mississippi,ms,28,,,,
24,Missouri,mo,29,,,,
25,Montana,mt,30,,,,
26,Nebraska,ne,31,,,,
27,Nevada,nv,32,,,,
28,New Hampshire,nh,33,,,,
29,New Jersey,nj,34,,,,
30,New Mexico,nm,35,,,,
31,New York,ny,36,,,,
32,North Carolina,nc,37,,,,
33,North Dakota,nd,38,,,,
34,Ohio,oh,39,,,,
35,Oklahoma,ok,40,,,,
36,Oregon,or,41,,,,
37,Pennsylvania,pa,42,,,,
38,Rhode Island,ri,44,,,,
39,South Carolina,sc,45,,,,
40,South Dakota,sd,46,,,,
41,Tennessee,tn,47,,,,
42,Texas,tx,48,,,,
43,Utah,ut,49,,,,
44,Vermont,vt,50,,,,
45,Virginia,va,51,,,,
46,Washington,wa,53,,,,
47,West Virginia,wv,54,,,,
48,Wisconsin,wi,55,,,,
49,Wyoming,wy,56,,,,
50,District of Columbia,dc,11,,,,

In [4]:
covid_deaths_2020_df['State'] = covid_deaths_2020_df['State'] .astype(str)
covid_deaths_2020_df.sort_values('State').reset_index(drop=True)

,State,State Abbreviation,FIPS,Total Population 2021,Total Cases 2020,Total Hospitalized 2020,Total Deaths 2020
0,Alabama,al,01,,,,
1,Alaska,ak,02,,,,
2,Arizona,az,04,,,,
3,Arkansas,ar,05,,,,
4,California,ca,06,,,,
5,Colorado,co,08,,,,
6,Connecticut,ct,09,,,,
7,Delaware,de,10,,,,
8,District of Columbia,dc,11,,,,
9,Florida,fl,12,,,,
10,Georgia,ga,13,,,,
11,Hawaii,hi,15,,,,
12,Idaho,id,16,,,,
13,Illinois,il,17,,,,
14,Indiana,in,18,,,,
15,Iowa,ia,19,,,,
16,Kansas,ks,20,,,,
17,Kentucky,ky,21,,,,
18,Louisiana,la,22,,,,
19,Maine,me,23,,,,
20,Maryland,md,24,,,,
21,Massachusetts,ma,25,,,,
22,Michigan,mi,26,,,,
23,Minnesota,mn,27,,,,
24,Mississippi,ms,28,,,,
25,Missouri,mo,29,,,,
26,Montana,mt,30,,,,
27,Nebraska,ne,31,,,,
28,Nevada,nv,32,,,,
29,New Hampshire,nh,33,,,,
30,New Jersey,nj,34,,,,
31,New Mexico,nm,35,,,,
32,New York,ny,36,,,,
33,North Carolina,nc,37,,,,
34,North Dakota,nd,38,,,,
35,Ohio,oh,39,,,,
36,Oklahoma,ok,40,,,,
37,Oregon,or,41,,,,
38,Pennsylvania,pa,42,,,,
39,Rhode Island,ri,44,,,,
40,South Carolina,sc,45,,,,
41,South Dakota,sd,46,,,,
42,Tennessee,tn,47,,,,
43,Texas,tx,48,,,,
44,Utah,ut,49,,,,
45,Vermont,vt,50,,,,
46,Virginia,va,51,,,,
47,Washington,wa,53,,,,
48,West Virginia,wv,54,,,,
49,Wisconsin,wi,55,,,,
50,Wyoming,wy,56,,,,

In [5]:
census_url = "https://api.census.gov/data/2021/acs/acs1?get=NAME,B01001_001E&for=state:"
covid_url = "https://api.covidtracking.com/v2/states/"

for index, row in covid_deaths_2020_df.iterrows():
    query_url = f"{census_url}{row['FIPS']}"
    response = requests.get(query_url).json()
    covid_deaths_2020_df.loc[index, "Total Population 2021"] = response[1][1]

for index, row in covid_deaths_2020_df.iterrows():
    query_url = f"{covid_url}{row['State Abbreviation']}/2020-12-31.json"
    response = requests.get(query_url).json()
    covid_deaths_2020_df.loc[index, "Total Cases 2020"] = response["data"]["cases"]["total"]["value"]

for index, row in covid_deaths_2020_df.iterrows():
    query_url = f"{covid_url}{row['State Abbreviation']}/2020-12-31.json"
    response = requests.get(query_url).json()
    covid_deaths_2020_df.loc[index, "Total Hospitalized 2020"] = response["data"]["outcomes"]["hospitalized"]["total"]["value"]
    
for index, row in covid_deaths_2020_df.iterrows():
    query_url = f"{covid_url}{row['State Abbreviation']}/2020-12-31.json"
    response = requests.get(query_url).json()
    covid_deaths_2020_df.loc[index, "Total Deaths 2020"] = response["data"]["outcomes"]["death"]["total"]["value"]
    
covid_deaths_2020_df

,State,State Abbreviation,FIPS,Total Population 2021,Total Cases 2020,Total Hospitalized 2020,Total Deaths 2020
0,Alabama,al,01,5039877,361226,34184,4827
1,Alaska,ak,02,732673,45461,1023,206
2,Arizona,az,04,7276316,520207,37257,8864
3,Arkansas,ar,05,3025891,225138,11358,3676
4,California,ca,06,39237836,2245379,None,25386
5,Colorado,co,08,5812069,334097,18598,4814
6,Connecticut,ct,09,3605597,185708,None,5995
7,Delaware,de,10,1003384,57456,None,926
8,Florida,fl,12,21781128,1300528,63741,21990
9,Georgia,ga,13,10799566,666452,42084,10934
10,Hawaii,hi,15,1441553,21832,1768,288
11,Idaho,id,16,1900923,139864,5567,1403
12,Illinois,il,17,12671469,963389,None,17978
13,Indiana,in,18,6805985,511485,34999,8263
14,Iowa,ia,19,3193079,239173,None,3891
15,Kansas,ks,20,2934582,222433,6760,2741
16,Kentucky,ky,21,4509394,265262,13488,2623
17,Louisiana,la,22,4624047,315275,None,7488
18,Maine,me,23,1372247,24201,1065,347
19,Maryland,md,24,6165129,276662,26636,5895
20,Massachusetts,ma,25,6984723,375178,16098,12423
21,Michigan,mi,26,10050811,528621,None,13018
22,Minnesota,mn,27,5707390,415302,21864,5323
23,Mississippi,ms,28,2949965,215811,8145,4787
24,Missouri,mo,29,6168187,392570,None,5519
25,Montana,mt,30,1104271,81555,3568,961
26,Nebraska,ne,31,1963692,165297,5220,1611
27,Nevada,nv,32,3143991,224731,None,3125
28,New Hampshire,nh,33,1388992,44028,902,759
29,New Jersey,nj,34,9267130,526985,47326,19042
30,New Mexico,nm,35,2115877,142864,9689,2477
31,New York,ny,36,19835913,974214,None,30040
32,North Carolina,nc,37,10551162,539545,None,6748
33,North Dakota,nd,38,774948,92495,3552,1289
34,Ohio,oh,39,11780017,700380,38334,8962
35,Oklahoma,ok,40,3986639,290936,17059,2489
36,Oregon,or,41,4246155,112260,6455,1468
37,Pennsylvania,pa,42,12964056,640325,None,15978
38,Rhode Island,ri,44,1095610,89541,6506,1809
39,South Carolina,sc,45,5190705,307507,14390,5296
40,South Dakota,sd,46,895376,99164,5672,1488
41,Tennessee,tn,47,6975218,586802,14531,6907
42,Texas,tx,48,29527941,1756172,None,27437
43,Utah,ut,49,3337975,276612,10956,1269
44,Vermont,vt,50,645570,7412,None,136
45,Virginia,va,51,8642274,349584,18041,5032
46,Washington,wa,53,7738692,242330,14571,3420
47,West Virginia,wv,54,1782959,85334,None,1338
48,Wisconsin,wi,55,5895908,520438,21350,5242
49,Wyoming,wy,56,578803,44409,1102,438
50,District of Columbia,dc,11,670050,28983,None,786

In [6]:
covid_deaths_2020_df.sort_values('State').reset_index(drop=True)

,State,State Abbreviation,FIPS,Total Population 2021,Total Cases 2020,Total Hospitalized 2020,Total Deaths 2020
0,Alabama,al,01,5039877,361226,34184,4827
1,Alaska,ak,02,732673,45461,1023,206
2,Arizona,az,04,7276316,520207,37257,8864
3,Arkansas,ar,05,3025891,225138,11358,3676
4,California,ca,06,39237836,2245379,None,25386
5,Colorado,co,08,5812069,334097,18598,4814
6,Connecticut,ct,09,3605597,185708,None,5995
7,Delaware,de,10,1003384,57456,None,926
8,District of Columbia,dc,11,670050,28983,None,786
9,Florida,fl,12,21781128,1300528,63741,21990
10,Georgia,ga,13,10799566,666452,42084,10934
11,Hawaii,hi,15,1441553,21832,1768,288
12,Idaho,id,16,1900923,139864,5567,1403
13,Illinois,il,17,12671469,963389,None,17978
14,Indiana,in,18,6805985,511485,34999,8263
15,Iowa,ia,19,3193079,239173,None,3891
16,Kansas,ks,20,2934582,222433,6760,2741
17,Kentucky,ky,21,4509394,265262,13488,2623
18,Louisiana,la,22,4624047,315275,None,7488
19,Maine,me,23,1372247,24201,1065,347
20,Maryland,md,24,6165129,276662,26636,5895
21,Massachusetts,ma,25,6984723,375178,16098,12423
22,Michigan,mi,26,10050811,528621,None,13018
23,Minnesota,mn,27,5707390,415302,21864,5323
24,Mississippi,ms,28,2949965,215811,8145,4787
25,Missouri,mo,29,6168187,392570,None,5519
26,Montana,mt,30,1104271,81555,3568,961
27,Nebraska,ne,31,1963692,165297,5220,1611
28,Nevada,nv,32,3143991,224731,None,3125
29,New Hampshire,nh,33,1388992,44028,902,759
30,New Jersey,nj,34,9267130,526985,47326,19042
31,New Mexico,nm,35,2115877,142864,9689,2477
32,New York,ny,36,19835913,974214,None,30040
33,North Carolina,nc,37,10551162,539545,None,6748
34,North Dakota,nd,38,774948,92495,3552,1289
35,Ohio,oh,39,11780017,700380,38334,8962
36,Oklahoma,ok,40,3986639,290936,17059,2489
37,Oregon,or,41,4246155,112260,6455,1468
38,Pennsylvania,pa,42,12964056,640325,None,15978
39,Rhode Island,ri,44,1095610,89541,6506,1809
40,South Carolina,sc,45,5190705,307507,14390,5296
41,South Dakota,sd,46,895376,99164,5672,1488
42,Tennessee,tn,47,6975218,586802,14531,6907
43,Texas,tx,48,29527941,1756172,None,27437
44,Utah,ut,49,3337975,276612,10956,1269
45,Vermont,vt,50,645570,7412,None,136
46,Virginia,va,51,8642274,349584,18041,5032
47,Washington,wa,53,7738692,242330,14571,3420
48,West Virginia,wv,54,1782959,85334,None,1338
49,Wisconsin,wi,55,5895908,520438,21350,5242
50,Wyoming,wy,56,578803,44409,1102,438

In [7]:
hospital_bed_df = pd.read_csv('2020 Hospital Beds By State Edited.csv')
covid_deaths_2020_df = covid_deaths_2020_df.merge(hospital_bed_df,how='left',on='State')
covid_deaths_2020_df['Death Rate 2020']=covid_deaths_2020_df['Total Deaths 2020']/covid_deaths_2020_df['Total Cases 2020']
covid_deaths_2020_df['Death Rate 2020']=covid_deaths_2020_df['Death Rate 2020'].map('{:.2%}'.format)
covid_deaths_2020_df

,State,State Abbreviation,FIPS,Total Population 2021,Total Cases 2020,Total Hospitalized 2020,Total Deaths 2020,State/Local Government,Non-Profit,For-Profit,Total Beds Per 1000 Capita,Death Rate 2020
0,Alabama,al,01,5039877,361226,34184,4827,1.40,0.84,0.82,3.06,1.34%
1,Alaska,ak,02,732673,45461,1023,206,0.23,1.58,0.36,2.17,0.45%
2,Arizona,az,04,7276316,520207,37257,8864,0.11,1.49,0.39,1.99,1.70%
3,Arkansas,ar,05,3025891,225138,11358,3676,0.36,2.16,0.63,3.16,1.63%
4,California,ca,06,39237836,2245379,None,25386,0.33,1.22,0.30,1.84,1.13%
5,Colorado,co,08,5812069,334097,18598,4814,0.38,1.12,0.41,1.91,1.44%
6,Connecticut,ct,09,3605597,185708,None,5995,0.05,1.99,0.05,2.09,3.23%
7,Delaware,de,10,1003384,57456,None,926,NaN,2.16,0.04,2.20,1.61%
8,Florida,fl,12,21781128,1300528,63741,21990,0.40,1.32,0.82,2.55,1.69%
9,Georgia,ga,13,10799566,666452,42084,10934,0.27,1.78,0.29,2.34,1.64%
10,Hawaii,hi,15,1441553,21832,1768,288,0.27,1.58,NaN,1.85,1.32%
11,Idaho,id,16,1900923,139864,5567,1403,0.48,1.03,0.41,1.91,1.00%
12,Illinois,il,17,12671469,963389,None,17978,0.12,2.24,0.12,2.49,1.87%
13,Indiana,in,18,6805985,511485,34999,8263,0.43,1.91,0.37,2.71,1.62%
14,Iowa,ia,19,3193079,239173,None,3891,0.89,1.90,0.06,2.85,1.63%
15,Kansas,ks,20,2934582,222433,6760,2741,0.99,1.39,0.81,3.19,1.23%
16,Kentucky,ky,21,4509394,265262,13488,2623,0.33,2.41,0.43,3.17,0.99%
17,Louisiana,la,22,4624047,315275,None,7488,0.55,2.01,0.68,3.25,2.38%
18,Maine,me,23,1372247,24201,1065,347,0.05,2.44,0.07,2.56,1.43%
19,Maryland,md,24,6165129,276662,26636,5895,NaN,1.81,0.01,1.82,2.13%
20,Massachusetts,ma,25,6984723,375178,16098,12423,0.06,1.82,0.37,2.25,3.31%
21,Michigan,mi,26,10050811,528621,None,13018,0.07,2.12,0.25,2.43,2.46%
22,Minnesota,mn,27,5707390,415302,21864,5323,0.29,2.14,NaN,2.43,1.28%
23,Mississippi,ms,28,2949965,215811,8145,4787,1.70,1.51,0.78,3.99,2.22%
24,Missouri,mo,29,6168187,392570,None,5519,0.42,2.20,0.40,3.01,1.41%
25,Montana,mt,30,1104271,81555,3568,961,0.20,3.06,0.19,3.46,1.18%
26,Nebraska,ne,31,1963692,165297,5220,1611,0.36,2.89,0.13,3.38,0.97%
27,Nevada,nv,32,3143991,224731,None,3125,0.21,0.61,1.26,2.08,1.39%
28,New Hampshire,nh,33,1388992,44028,902,759,NaN,1.65,0.38,2.04,1.72%
29,New Jersey,nj,34,9267130,526985,47326,19042,0.15,2.00,0.21,2.36,3.61%
30,New Mexico,nm,35,2115877,142864,9689,2477,0.34,0.75,0.69,1.79,1.73%
31,New York,ny,36,19835913,974214,None,30040,0.46,2.06,NaN,2.52,3.08%
32,North Carolina,nc,37,10551162,539545,None,6748,0.62,1.35,0.11,2.08,1.25%
33,North Dakota,nd,38,774948,92495,3552,1289,NaN,4.22,0.09,4.31,1.39%
34,Ohio,oh,39,11780017,700380,38334,8962,0.25,2.27,0.21,2.73,1.28%
35,Oklahoma,ok,40,3986639,290936,17059,2489,0.50,1.54,0.76,2.81,0.86%
36,Oregon,or,41,4246155,112260,6455,1468,0.21,1.38,0.06,1.64,1.31%
37,Pennsylvania,pa,42,12964056,640325,None,15978,0.00,2.46,0.27,2.73,2.50%
38,Rhode Island,ri,44,1095610,89541,6506,1809,NaN,2.00,NaN,2.00,2.02%
39,South Carolina,sc,45,5190705,307507,14390,5296,0.67,1.00,0.52,2.19,1.72%
40,South Dakota,sd,46,895376,99164,5672,1488,0.24,4.35,0.23,4.82,1.50%
41,Tennessee,tn,47,6975218,586802,14531,6907,0.48,1.49,0.80,2.77,1.18%
42,Texas,tx,48,29527941,1756172,None,27437,0.32,0.99,0.96,2.28,1.56%
43,Utah,ut,49,3337975,276612,10956,1269,0.34,0.93,0.53,1.80,0.46%
44,Vermont,vt,50,645570,7412,None,136,NaN,2.08,NaN,2.08,1.83%
45,Virginia,va,51,8642274,349584,18041,5032,0.21,1.48,0.42,2.10,1.44%
46,Washington,wa,53,7738692,242330,14571,3420,0.41,1.15,0.02,1.58,1.41%
47,West Virginia,wv,54,1782959,85334,None,1338,0.23,2.74,0.54,3.52,1.57%
48,Wisconsin,wi,55,5895908,520438,21350,5242,0.00,1.99,0.08,2.08,1.01%
49,Wyoming,wy,56,578803,44409,1102,438,2.37,0.64,0.35,3.35,0.99%
50,District of Columbia,dc,11,670050,28983,None,786,NaN,3.70,1.01,4.70,2.71%

In [8]:
hospital_bed_df

,State,State/Local Government,Non-Profit,For-Profit,Total Beds Per 1000 Capita
0,United States,0.34,1.65,0.39,2.38
1,Alabama,1.40,0.84,0.82,3.06
2,Alaska,0.23,1.58,0.36,2.17
3,Arizona,0.11,1.49,0.39,1.99
4,Arkansas,0.36,2.16,0.63,3.16
5,California,0.33,1.22,0.30,1.84
6,Colorado,0.38,1.12,0.41,1.91
7,Connecticut,0.05,1.99,0.05,2.09
8,Delaware,NaN,2.16,0.04,2.20
9,District of Columbia,NaN,3.70,1.01,4.70
10,Florida,0.40,1.32,0.82,2.55
11,Georgia,0.27,1.78,0.29,2.34
12,Hawaii,0.27,1.58,NaN,1.85
13,Idaho,0.48,1.03,0.41,1.91
14,Illinois,0.12,2.24,0.12,2.49
15,Indiana,0.43,1.91,0.37,2.71
16,Iowa,0.89,1.90,0.06,2.85
17,Kansas,0.99,1.39,0.81,3.19
18,Kentucky,0.33,2.41,0.43,3.17
19,Louisiana,0.55,2.01,0.68,3.25
20,Maine,0.05,2.44,0.07,2.56
21,Maryland,NaN,1.81,0.01,1.82
22,Massachusetts,0.06,1.82,0.37,2.25
23,Michigan,0.07,2.12,0.25,2.43
24,Minnesota,0.29,2.14,NaN,2.43
25,Mississippi,1.70,1.51,0.78,3.99
26,Missouri,0.42,2.20,0.40,3.01
27,Montana,0.20,3.06,0.19,3.46
28,Nebraska,0.36,2.89,0.13,3.38
29,Nevada,0.21,0.61,1.26,2.08
30,New Hampshire,NaN,1.65,0.38,2.04
31,New Jersey,0.15,2.00,0.21,2.36
32,New Mexico,0.34,0.75,0.69,1.79
33,New York,0.46,2.06,NaN,2.52
34,North Carolina,0.62,1.35,0.11,2.08
35,North Dakota,NaN,4.22,0.09,4.31
36,Ohio,0.25,2.27,0.21,2.73
37,Oklahoma,0.50,1.54,0.76,2.81
38,Oregon,0.21,1.38,0.06,1.64
39,Pennsylvania,0.00,2.46,0.27,2.73
40,Rhode Island,NaN,2.00,NaN,2.00
41,South Carolina,0.67,1.00,0.52,2.19
42,South Dakota,0.24,4.35,0.23,4.82
43,Tennessee,0.48,1.49,0.80,2.77
44,Texas,0.32,0.99,0.96,2.28
45,Utah,0.34,0.93,0.53,1.80
46,Vermont,NaN,2.08,NaN,2.08
47,Virginia,0.21,1.48,0.42,2.10
48,Washington,0.41,1.15,0.02,1.58
49,West Virginia,0.23,2.74,0.54,3.52
50,Wisconsin,0.00,1.99,0.08,2.08
51,Wyoming,2.37,0.64,0.35,3.35